# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 783)
        MainWindow.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{rgb(161, 161, 161);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 115, 85, 17))
        self.label_10.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_10.setObjectName("label_10")
        self.imeisilbutton = QtWidgets.QPushButton(self.centralwidget)
        self.imeisilbutton.setGeometry(QtCore.QRect(570, 390, 130, 40))
        self.imeisilbutton.setStyleSheet("QPushButton{\n"
"background-color:rgb(177, 29, 32);\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(255, 180, 181);\n"
"color:rgb(38, 38, 38);\n"
"}")
        self.imeisilbutton.setObjectName("imeisilbutton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(11, 390, 103, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(120, 390, 95, 30))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.calisannosil = QtWidgets.QPushButton(self.centralwidget)
        self.calisannosil.setGeometry(QtCore.QRect(270, 390, 130, 40))
        self.calisannosil.setStyleSheet("QPushButton{\n"
"background-color:rgb(177, 29, 32);\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(255, 180, 181);\n"
"color:rgb(38, 38, 38);\n"
"}")
        self.calisannosil.setObjectName("calisannosil")
        self.buton = QtWidgets.QPushButton(self.centralwidget)
        self.buton.setEnabled(True)
        self.buton.setGeometry(QtCore.QRect(420, 390, 130, 40))
        self.buton.setMinimumSize(QtCore.QSize(0, 0))
        self.buton.setStyleSheet("QPushButton{\n"
"background-color:rgb(110, 166, 110);\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(226, 255, 237);\n"
"color:rgb(38, 38, 38);\n"
"}")
        self.buton.setObjectName("buton")
        self.adsoyad = QtWidgets.QLineEdit(self.centralwidget)
        self.adsoyad.setGeometry(QtCore.QRect(375, 110, 154, 23))
        self.adsoyad.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.adsoyad.setObjectName("adsoyad")
        self.calisannocombo = QtWidgets.QComboBox(self.centralwidget)
        self.calisannocombo.setGeometry(QtCore.QRect(106, 110, 144, 23))
        self.calisannocombo.setStyleSheet("QComboBox{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color:rgb(0, 0, 0);\n"
"}")
        self.calisannocombo.setObjectName("calisannocombo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(285, 113, 81, 20))
        self.label_2.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_2.setObjectName("label_2")
        self.cihazdurumu = QtWidgets.QLineEdit(self.centralwidget)
        self.cihazdurumu.setGeometry(QtCore.QRect(1000, 110, 154, 23))
        self.cihazdurumu.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:50px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.cihazdurumu.setObjectName("cihazdurumu")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(880, 113, 111, 20))
        self.label_18.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(575, 113, 41, 17))
        self.label_3.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(620, 110, 200, 23))
        self.comboBox.setStyleSheet("QComboBox\n"
"{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color:black;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 81, 20))
        self.label_4.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_4.setObjectName("label_4")
        self.pcmodel = QtWidgets.QLineEdit(self.centralwidget)
        self.pcmodel.setGeometry(QtCore.QRect(650, 160, 154, 23))
        self.pcmodel.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.pcmodel.setObjectName("pcmodel")
        self.pcimei = QtWidgets.QLabel(self.centralwidget)
        self.pcimei.setGeometry(QtCore.QRect(880, 160, 100, 17))
        self.pcimei.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.pcimei.setObjectName("pcimei")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(1000, 160, 154, 23))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(567, 160, 71, 20))
        self.label_11.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_11.setObjectName("label_11")
        self.pcmarka = QtWidgets.QLineEdit(self.centralwidget)
        self.pcmarka.setGeometry(QtCore.QRect(106, 160, 144, 23))
        self.pcmarka.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.pcmarka.setObjectName("pcmarka")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(910, 212, 31, 17))
        self.label_15.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_15.setObjectName("label_15")
        self.SSD = QtWidgets.QLineEdit(self.centralwidget)
        self.SSD.setGeometry(QtCore.QRect(650, 210, 154, 23))
        self.SSD.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.SSD.setObjectName("SSD")
        self.islemci = QtWidgets.QComboBox(self.centralwidget)
        self.islemci.setGeometry(QtCore.QRect(375, 210, 154, 23))
        self.islemci.setStyleSheet("QComboBox\n"
"{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color:rgb(0, 0, 0);\n"
"}")
        self.islemci.setObjectName("islemci")
        self.islemci.addItem("")
        self.islemci.addItem("")
        self.islemci.addItem("")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(610, 210, 26, 17))
        self.label_14.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 160, 81, 20))
        self.label_6.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_6.setObjectName("label_6")
        self.pcbarkod = QtWidgets.QLineEdit(self.centralwidget)
        self.pcbarkod.setGeometry(QtCore.QRect(375, 160, 154, 23))
        self.pcbarkod.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"input required=\"required\";\n"
"}")
        self.pcbarkod.setObjectName("pcbarkod")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(281, 210, 61, 20))
        self.label_13.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_13.setObjectName("label_13")
        self.ram = QtWidgets.QComboBox(self.centralwidget)
        self.ram.setGeometry(QtCore.QRect(1000, 210, 154, 23))
        self.ram.setStyleSheet("QComboBox\n"
"{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color:rgb(0, 0, 0);}")
        self.ram.setObjectName("ram")
        self.ram.addItem("")
        self.ram.addItem("")
        self.ram.addItem("")
        self.ram.addItem("")
        self.ram.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 390, 170, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(125, 125, 186);\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(227, 221, 255);\n"
"color:rgb(38, 38, 38);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.subedeyeni = QtWidgets.QPushButton(self.centralwidget)
        self.subedeyeni.setGeometry(QtCore.QRect(910, 390, 150, 40))
        self.subedeyeni.setStyleSheet("QPushButton{\n"
"background-color:rgb(110, 166, 110);\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(226, 255, 237);\n"
"color:rgb(38, 38, 38);\n"
"}")
        self.subedeyeni.setObjectName("subedeyeni")
        self.telserino = QtWidgets.QLineEdit(self.centralwidget)
        self.telserino.setGeometry(QtCore.QRect(1000, 270, 144, 21))
        self.telserino.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.telserino.setObjectName("telserino")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(880, 270, 87, 18))
        self.label_17.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_17.setObjectName("label_17")
        self.telmarka = QtWidgets.QLineEdit(self.centralwidget)
        self.telmarka.setGeometry(QtCore.QRect(100, 270, 144, 21))
        self.telmarka.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.telmarka.setObjectName("telmarka")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 270, 78, 18))
        self.label_7.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_7.setObjectName("label_7")
        self.telimei = QtWidgets.QLineEdit(self.centralwidget)
        self.telimei.setGeometry(QtCore.QRect(375, 270, 154, 21))
        self.telimei.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.telimei.setObjectName("telimei")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(280, 270, 62, 18))
        self.label_8.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 270, 87, 18))
        self.label_9.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(650, 270, 144, 21))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.telmodel = QtWidgets.QLineEdit(self.centralwidget)
        self.telmodel.setGeometry(QtCore.QRect(380, 320, 154, 23))
        self.telmodel.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(90, 86, 88);\n"
"border-radius:30px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.telmodel.setObjectName("telmodel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 320, 91, 20))
        self.label.setStyleSheet("QLabel{\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"}")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1256, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UYGULAMA"))
        self.label_10.setText(_translate("MainWindow", "ÇALIŞAN NO."))
        self.imeisilbutton.setText(_translate("MainWindow", "Pc Parkod ile Sil"))
        self.label_5.setText(_translate("MainWindow", "Tarih Girin"))
        self.calisannosil.setText(_translate("MainWindow", "Çalışan no ile sil"))
        self.buton.setText(_translate("MainWindow", "Çalışan no ile ekle"))
        self.adsoyad.setPlaceholderText(_translate("MainWindow", "AD SOYAD"))
        self.label_2.setText(_translate("MainWindow", "AD SOYAD"))
        self.cihazdurumu.setPlaceholderText(_translate("MainWindow", "CİHAZ DURUM"))
        self.label_18.setText(_translate("MainWindow", "CİHAZ DURUMU"))
        self.label_3.setText(_translate("MainWindow", "ŞUBE"))
        self.label_4.setText(_translate("MainWindow", "PC MARKA"))
        self.pcimei.setText(_translate("MainWindow", "PC SERİ NO"))
        self.label_11.setText(_translate("MainWindow", "PC MODEL"))
        self.label_15.setText(_translate("MainWindow", "RAM"))
        self.islemci.setItemText(0, _translate("MainWindow", "İ5"))
        self.islemci.setItemText(1, _translate("MainWindow", "İ7"))
        self.islemci.setItemText(2, _translate("MainWindow", "İ9"))
        self.label_14.setText(_translate("MainWindow", "SSD"))
        self.label_6.setText(_translate("MainWindow", "PC BARKOD"))
        self.label_13.setText(_translate("MainWindow", "İŞLEMCİ"))
        self.ram.setItemText(0, _translate("MainWindow", "4 GB "))
        self.ram.setItemText(1, _translate("MainWindow", "8 GB"))
        self.ram.setItemText(2, _translate("MainWindow", "16 GB"))
        self.ram.setItemText(3, _translate("MainWindow", "32 GB"))
        self.ram.setItemText(4, _translate("MainWindow", "64 GB"))
        self.pushButton.setText(_translate("MainWindow", "Çalışan No ile Tayin Et"))
        self.subedeyeni.setText(_translate("MainWindow", "Şubede Yeni Personel"))
        self.label_17.setText(_translate("MainWindow", "TEL SERİ NO"))
        self.label_7.setText(_translate("MainWindow", "TEL MARKA"))
        self.label_8.setText(_translate("MainWindow", "TEL İMEİ"))
        self.label_9.setText(_translate("MainWindow", "TEL BARKOD"))
        self.label.setText(_translate("MainWindow", "TEL MODEL"))
